//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maseya.Snes.Tests.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snes.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;AddressMode&quot;: &quot;LoRom&quot;,
        ///    &quot;FileName&quot;: &quot;Aladdin (E)&quot;,
        ///    &quot;HiRom&quot;: &quot;AACqAP//f5/HgP//v5+/qr+fn5+eqgD//8DAqgDAwMDBOP8AAAAC/wCgAP//AgD/zv/9AQAAAH8F4jXSLcKgTYoA/v//IP/vfwEciZQAFgU=&quot;,
        ///    &quot;LoRom&quot;: &quot;XOmIgAADAAEB8BcAAA8Pf0FMQURESU4gICAgICAgICAgICAgIDAACwACCAA88MMPRWcyM7D/rP+s/6T/rP+o/1gsIC+w/6z/rP+s/wCArP8=&quot;,
        ///    &quot;Size&quot;: 1310720
        ///  },
        ///  {
        ///    &quot;AddressMode&quot;: &quot;LoRom&quot;,
        ///    &quot;FileName&quot;: &quot;Aladdin (F)&quot;,
        ///    &quot;HiRom&quot;: &quot;AAAAAAAAAAAAAAAAAAAAAEACkggOAIhaggI6ABcAliQKYEciOIlDgqAAg0AVyA0STFQCSAoIAQJIgdgiKYBC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RomFormatTestData
        {
            get
            {
                return ResourceManager.GetString("RomFormatTestData", resourceCulture);
            }
        }
    }
}
